repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies: [ types-all ]
        args: [ --strict ]
        files: ^app/.*\.py$
