[tool.poetry]
name = "fitpet-scraper"
version = "0.1.0"
description = ""
authors = ["Raynor <jonggu.woo@fitpet.co.kr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
sqlalchemy = "^2.0.43"
httpx = "^0.28.1"
argparse = "^1.4.0"
celery = { extras = ["redis"], version = "^5.5.3" }
celery-once = "^3.0.1"
celery-types = "^0.23.0"
pydantic = "^2.11.7"
pydantic-settings = "^2.10.1"
black = "^25.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ["py312"]
