import enum


class ErrorCodeEnum(enum.Enum):
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    KEYWORD_ALREADY_EXISTS = "KEYWORD_ALREADY_EXISTS"
    UNSUPPORTED_CHANNEL = "UNSUPPORTED_CHANNEL"
